export const products  = [
    {
      id: 1,
      title: 'Yellow Pail',
    },
    {
      id: 2,
      title: 'Green Pail',
    },
  ]

 export const genders = [
    { 
        value: 'Male',
        label: 'Male' 
    },
    { 
        value: 'Female', 
        label: 'Female' 
    },
]

export const ageGroups = [
    { value: '1 year old', label: '1 year old' },
    { value: '2 years old', label: '2 years old' },
    { value: '3 years old', label: '3 years old' },
    { value: '4 years old', label: '4 years old' },
    { value: '5 years old', label: '5 years old' },
    { value: '6 years old', label: '6 years old' },
    { value: '7 years old', label: '7 years old' },
    { value: '8 years old', label: '8 years old' },
    { value: '9 years old', label: '9 years old' },
    { value: '10 years old', label: '10 years old' },
    { value: '11 years old', label: '11 years old' },
    { value: '12 years old', label: '12 years old' },
    { value: '13 years old', label: '13 years old' },
    { value: '14 years old', label: '14 years old' },
    { value: '15 years old', label: '15 years old' },
    { value: '16 years old', label: '16 years old' },
    { value: '17 years old', label: '17 years old' },
    { value: '18 years old', label: '18 years old' },
    { value: '1 month old', label: '1 month old' },
    { value: '2 months old', label: '2 months old' },
    { value: '3 months old', label: '3 months old' },
    { value: '4 months old', label: '4 months old' },
    { value: '5 months old', label: '5 months old' },
    { value: '6 months old', label: '6 months old' },
    { value: '7 months old', label: '7 months old' },
    { value: '8 months old', label: '8 months old' },
    { value: '9 months old', label: '9 months old' },
    { value: '10 months old', label: '10 months old' },
    { value: '11 months old', label: '11 months old' },
    { value: '12 months old', label: '12 months old' }
]

export const stateOptions = [
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AS', label: 'American Samoa' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'DC', label: 'District Of Columbia' },
    { value: 'FM', label: 'Federated States Of Micronesia' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'GU', label: 'Guam' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MH', label: 'Marshall Islands' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'MP', label: 'Northern Mariana Islands' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PW', label: 'Palau' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'PR', label: 'Puerto Rico' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VI', label: 'Virgin Islands' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' },
  ];
  
  export default {
      products,
      genders,
      ageGroups,
      stateOptions
  }